typedef enum {
    ORBIT_SUCCESS = 0,
    ORBIT_ERR_PERIAPSIS_INTERSECTS_SURFACE,
    ORBIT_ERR_INVALID_SATELLITE_COUNT,
    ORBIT_ERR_APOAPSIS_OUTSIDE_SOI,
    ORBIT_ERR_MISSING_PRIMARY,
    ORBIT_ERR_NOT_ELLIPTICAL,
    ORBIT_ERR_NOT_ELLIPTICAL_OR_CIRCULAR,
    ORBIT_ERR_NOT_INTERSECTING,
} OrbitError;